### ISSUE TITLE
hal is being removed from core

### ISSUE THREAD

**Issue by Natkeeran** [Islandora/jsonld#63]
As of Drupal 9.4, hal is being removed from Drupal core. More info here: https://www.drupal.org/node/3223395#s-hal 
 
**What existing behavior do you want changed?**
 We will need to change the composer to install the hal from the contrib.

**Comment by whikloj** [comment]
Hal is being deprecated as of Drupal 9.4, it is not being removed until Drupal 10. Hal 1.0 only support `^9.4 || ^10` so this change ends Islandora support for Drupal 8 entirely.

**Comment by whikloj** [comment]
Actually it also ends support for all versions of Drupal before 9.4

**Comment by rosiel** [comment]
Thus we need to update [jsonld's info.yml](https://github.com/Islandora/jsonld/blob/2.x/jsonld.info.yml) file.

**Comment by rosiel** [comment]
We still list `hal` as a dependency in the info.yml file. But hal isn't listed in this composer.json. Does this mean that in Playbook and ISLE, we'll need to explicitly `composer require drupal/hal`?

**Comment by rosiel** [comment]
It seems to me like new sites loading on Drupal 9 should be using the external (contrib, non-deprecated) version of the HAL module.  And it seems (maybe it's just the theme?) that they're getting more adamant with the warning messages. 

The new module seems to have the same name, because when i did a `composer require` in the sandbox, the Extend list stopped showing "Hal (deprecated)" and only showed "Hal".   also I did `drupal/hal` not `drupal/hal-hal` which might have been... an earlier naming? [here's the contrib module now](https://www.drupal.org/project/hal). 

For now, a stop-gap measure could be that we explicitly include it in the starter site using `composer require 'drupal/hal:^1.0'`. If we do it in the module, then the module might be locked to either Drupal 9 (hal 1.x) or Drupal 10 (hal 2.x)/ Unless we can include "either or" in jsonld's composer requirements?

**Comment by whikloj** [comment]
I'm fine with upgrading to include `drupal/hal:^1.0`. 

I would suggest that this should/could be a major version as it would not support past versions of Drupal. Once Drupal 10 is out we can then cut another major version to upgrade the requirement.

We should do some testing of how you can effectively upgrade from using the internal HAL to the external HAL, so we have some good instructions.
